export const DASHBOARD_STRINGS = {
  LOADING_OPPS: "Se încarcă oportunitățile de azi...",
  NO_OPPS_TITLE: "Oportunități noi astăzi",
  NO_OPPS_MESSAGE: "Nu au fost postate oportunități noi astăzi. Revino mâine!",
  OPPS_HEADER: "🔥 Oportunități postate azi",
  VIEW_ALL: "Vezi toate",
  NO_IMAGE_PLACEHOLDER: "No Image",
  DEADLINE_PREFIX: "Deadline: ",
  LOGIN_POINTS_TOAST: "Ai primit 5 puncte pentru login-ul de azi! 💎",
  BADGE_UNLOCK_TOAST: (label: string) => `Felicitări! Ai deblocat badge-ul "${label}" și ai primit 5 puncte! 🏅`,
  REPAIR_ERROR_POINTS: "Nu ai suficiente puncte pentru repair!",
  REPAIR_SUCCESS: "Streak reparat cu succes! 🛠️",
  REPAIR_ERROR_GENERIC: "Eroare la reparare",
  AUTO_FREEZE_MESSAGE: "Bine că ai revenit! 💛 Ți-am „înghețat” streak-ul pentru o zi lipsă — se mai întâmplă.",
  GAP_MESSAGE: (days: number) => `Ai avut o pauză de ${days} zile`,
  REPAIR_PROMPT: "Poți repara streakul:",
  REPAIR_BUTTON: "Repară pentru 20 puncte",
  LAST_FREEZE_LABEL: "Ultimul auto-freeze:",
  LAST_REPAIR_LABEL: "Ultimul repair:",
  STATS_POINTS: "Puncte",
  STATS_BADGES: "Badge-uri",
  STATS_CURRENT_BADGE: "Badge-ul tău actual",
  NO_BP_BADGE: "Niciun badge de streak deblocat",
  MAP_LINK: "🗺️ Mapa progres"
};
